---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: texlive/texlive
    commands:
      - tlmgr option repository https://ctan.gutenberg-asso.fr/systems/texlive/tlnet
      - tlmgr update --self --all
      - latexmk sbabook
      - latexmk sbabook.bod
      - latexmk sbabook.spiral

  - name: build log
    image: alpine
    commands:
      - cat *.log
    when:
      status: [failure, success]

---
kind: pipeline
type: docker
name: minimal

steps:
  - name: build
    image: texlive/texlive:latest-minimal
    pull: always
    commands:
      - tlmgr option repository https://ctan.gutenberg-asso.fr/systems/texlive/tlnet
      - tlmgr update --self --all
      - tlmgr install latex-bin latexmk
      - xargs tlmgr install < texlive-2024.deps
      - tlmgr path add
      - latexmk sbabook
      - latexmk sbabook.bod
      - latexmk sbabook.spiral

  - name: build log
    image: alpine
    commands:
      - cat *.log
    when:
      status: [failure, success]
