version: ~> 1.0

env:
  global:
    - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  jobs:
    - TEXLIVE_RELEASE=rolling
    - TEXLIVE_RELEASE=2018

install:
  - ./ci/install-texlive

script:
  - latexmk

deploy:
  - provider: releases
    edge: true
    api_key:
      secure: 0VV/C2lRToLm/PzZd4tVWOGGVjgRi11nj4VRw/D93Y1XTy2IWoyctWg/02OpZ+vzmMjT9dk/V2ZyfsYZT/dTSVT2HVPW8n4HSlBDqHhVaEGEKEd2YxLw/V1yVehco16gAtaDAFCZITW2Kod9hiIRoRTcInkCyT4zKrco6v7XmSY=
    file: sbabook.pdf
    on:
      tags: true
      condition: $TEXLIVE_RELEASE = rolling
